pipeline:
  identifier: Build_jhttp_1698733863626
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: Demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698733812378
        repoName: jhttp
  stages:
    - step:
        type: Run
        identifier: build_java_app
        name: Build Java App
        spec:
          shell: Sh
          command: |-
            echo "Welcome to Harness CI"
            mvn -B package --file pom.xml
      platform:
        arch: Amd64
        os: Linux
      runtime:
        spec: {}
        type: Cloud
      type: CI
